clan_creation_cost:
   - 5000
   - 15000
   - 25000
clan_home_cd:
   - 3
   - 2
   - 1
clan_bank:
   - 20000
   - 50000
   - 100000
clan_capacity:
   - 10
   - 25
   - 50
clan_sethome_cost: 1000
clan_msg: "&7[&2ClanChat&7] &r&a%s&r: &a%s"